on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jdv52/vt-cro-pio-ci:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build the project
        run: pio run
